language: python
python:
- '3.8'
install:
- pip install -r requirements-travis.txt
script:
- python manage.py test
deploy:
  provider: heroku
  api_key:
    secure: Kd48oek5sFks6AcL2gCnKfX9ptEDNODCAOZXRYy4PfDdFBUm1nvnTkCoiV1ic6ND5ihxxhCyZEJSG4NMFWdMg5F9d/LEDTpwPeHNbQnBsVCEpxFgU/NVv4/OiBxMkwPI4qt5R95z4ypq2ubFuwWIx58GHRg4UP1C1oe4zVzPQL5RLmP5mHwScF+/T7mFQarHJTZPJD2yNm9ew9YR1oeOBqTEZ2cKOdFkjlIuMOPYzLtEwiXdkWA6CPOCpyRXg1t+sRlJYQl9tBy+YX2OXofCAhKdHCezD+duM2YBwS92QwCrmlSA3NkMCG4wbXgmfODDsNl9gp97n4jL5XFG7BpZF9v9T3yrPLBFx0axaXMcz3dgunwmjQNjLviUF6guQpQj3vITlnbcFZmDxbcYjjTIl8L7ycJVdXK/J6Kng9T1jLkGJETb85VTrX94NFdFTytai6pPEV6fHkRCSScjeABAgK6rpkTzzdZfaKIlOMK+EqCm/QOyJvAwx5lhQyvqRRk0Tegvfx3UZ0/SS2SFbx+zKZTYuchEb73/qOOpdZDkWXWAB/EB/TteCeGceQAqMKYh54g3hFtEvuP0DOxYMTQZK8xv75z2mnBAp8Zs/coWbfmV8u5D/kzVwnNQezze+sBNn715Sg1HlXUXR9neEugAFim2YBEZdTEFCKLKbfSzlC4=
  app: staff-textbookexchange-f20
  on:
    repo: uva-cs3240-f20/Staff-TextbookExchange
